cryptonews/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name="home"),
	path('costs/', views.costs, name="costs")
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('cryptonews.urls', 'cryptonews'), namespace="cryptonews")),
]

cryptonews/models.py
from django.db import models

# Create your models here.

cryptonews/views.py
from django.shortcuts import render
import requests
import json

def home(request):
	news_request = requests.get("https://min-api.cryptocompare.com/data/v2/news/?lang=EN")
	data = json.loads(news_request.content)
	return render(request, 'cryptonews/home.html', {'request': data})


def costs(request):
	if request.method == 'POST':
		crypto = request.POST['crypto']
		crypto = crypto.upper() 
		crypto_request = requests.get("https://min-api.cryptocompare.com/data/pricemultifull?fsyms=" + crypto + "&tsyms=USD")
		data = json.loads(crypto_request.content)
		return render(request, 'cryptonews/costs.html', {'request': data})
	else:
		price_request = requests.get("https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC,ETH,XRP,BCH,EOS,LTC,XLM,ADA,USDT,MIOTA,TRX&tsyms=USD")
		price = json.loads(price_request.content)
		return render(request, 'cryptonews/costs.html', {'price': price})

cryptonews/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>News about crypto currency</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
      <a class="navbar-brand" href="/">Crypto News</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cryptonews:costs' %}">Crypto Currencies</a>
          </li>
         
          
        </ul>
        <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'cryptonews:costs' %}">
          {% csrf_token %}
          <input class="form-control mr-sm-2" type="search" placeholder="Search Crypto" aria-label="Search" name="crypto">
          <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <div class="container" style="margin-top: 20px">
      {% block content %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

cryptonews/templates/cryptonews/costs.html
{% extends 'base.html' %}

{% block content %}

	{% if not request.method == 'POST' %}
		<table class="table table-striped table-bordered table-hover table-sm">
		  <thead>
		    <tr>
		      <th scope="col">Name </th>
		      <th scope="col">Price</th>
		      <th scope="col">24h High</th>
		      <th scope="col">24h Low</th>
		      <th scope="col">Market Cap</th>
		    </tr>
		  </thead>
	  	<tbody>
				{% for key,value in price.DISPLAY.items %}
			    <tr>
			      <td>{{ key }}</td>
			      <td>{{ value.USD.PRICE }}</td>
			      <td>{{ value.USD.HIGHDAY }}</td>
			      <td>{{ value.USD.LOWDAY }}</td>
			      <td>{{ value.USD.MKTCAP }}</td>
			    </tr>
				{% endfor %}
		  </tbody>
		</table>
	{% else %}
		{% if request.Response %}
			Sorry, {{ quote }} doesn't exist. Please Try Again...
		{% endif %}
		{% for key, value in request.DISPLAY.items %}
			<div class="jumbotron">
			  <h1 class="display-4">{{ key }}</h1>
			  <strong>Name</strong>: {{ key }}<br/>
	      <strong>Price</strong>: {{ value.USD.PRICE }}<br/>
	      <strong>Day High</strong>: {{ value.USD.HIGHDAY }}<br/>
	      <strong>Day Low</strong>: {{ value.USD.LOWDAY }}<br/>
	      <strong>Market Cap</strong>: {{ value.USD.MKTCAP }}<br/>
			</div>  
	    	<br/><br/>
		{% endfor %}
	{% endif %}
{% endblock %}

cryptonews/templates/cryptonews/home.html
{% extends 'base.html' %}

{% block content %}
	<div class="jumbotron">
	  <h1 class="display-4">Crypto Currency Network</h1>
	  <p class="lead">Your source for geting information about different crypto currencies and block chain.</p>
	</div>
	<div class="container">
		<div class="row">
			{% for data in request.Data %}
				<a href="{{ data.url }}" target="_blank" style="color: inherit; text-decoration: none">
					<div class="card" style="width: 20rem; margin: 20px; height: 650px">
					  <img src="{{ data.imageurl }}" class="card-img-top" alt="{{ data.source }}">
					  <div class="card-body">
					    <h5 class="card-title">{{ data.title }}</h5>
					    <p class="card-text">{{ data.body|truncatewords:30|linebreaks }}</p>
					  </div>
					</div>
				</a>			
			{% endfor %}
		</div>
	</div>
{% endblock %}